# Generated by Django 4.2.7 on 2023-12-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(max_length=15, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=2000)),
                ('current_location', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('estimated_delivery_date', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('notice', models.CharField(max_length=20000)),
                ('map', models.CharField(max_length=20000)),
            ],
        ),
    ]
