# Generated by Django 5.2 on 2025-06-23 11:08

import myApp.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_contacts_newsletter_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackDatas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_Number', models.CharField(blank=True, default=myApp.utils.create_new_ref_number, editable=False, max_length=10, unique=True)),
                ('ship_from', models.CharField(max_length=2000)),
                ('ship_to', models.CharField(max_length=200)),
                ('sender_email', models.CharField(max_length=200)),
                ('sender_phone', models.CharField(max_length=200)),
                ('sender_address', models.CharField(max_length=2000)),
                ('receiver_email', models.CharField(max_length=200)),
                ('receiver_phone', models.CharField(max_length=200)),
                ('receiver_address', models.CharField(max_length=2000)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.CharField(max_length=200)),
                ('customer_address', models.CharField(max_length=2000)),
                ('package', models.CharField(max_length=2000)),
                ('shipment_mode', models.CharField(max_length=200)),
                ('expected_delivery_date', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('package_weight', models.CharField(max_length=200)),
                ('carrier', models.CharField(max_length=200)),
                ('carrier_number', models.CharField(default=myApp.utils.carrier_ref, editable=False, max_length=20000)),
                ('map', models.CharField(blank=True, max_length=20000, null=True)),
                ('current_location', models.CharField(max_length=200)),
                ('product_id', models.CharField(default=myApp.utils.product_ref, editable=False, max_length=13)),
                ('customer_ref', models.CharField(default=myApp.utils.customer_ref, editable=False, max_length=200)),
                ('comment', models.CharField(max_length=20000)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='TrackingData',
        ),
    ]
