# Generated by Django 5.2 on 2025-06-23 11:49

import myApp.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_trackdatas_delete_trackingdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackdatas',
            name='track_Number',
            field=models.CharField(blank=True, default=myApp.utils.create_new_ref_number, editable=False, max_length=10000, unique=True),
        ),
    ]
